### ISSUE TITLE
Abyss Realmstone Unobtainable

### ISSUE THREAD

**Issue by Fleega** [Tslat/Advent-Of-Ascension#1080]
**Mod Version**
What version of the mod are you on?
3.2.1
**Describe the bug**
Blank Realmstone cannot transform into the Abyss Realmstone when attempting to perform its task.
**To Reproduce**
Steps to reproduce the behaviour:
Get a blank realmstone
Get the 3 wither skulls and 4 soul sand for the wither
Summon the wither
Cry about it

**Expected behavior**
I was clearly promised an Abyss Realmstone for my dangerous task

**Comment by Fleega** [comment]
i'm no good with making these

**Comment by Tslat** [comment]
Fixed

**Comment by peterwyy** [comment]
I'm afraid it's still not fixed. The exact same thing happened in Minecraft 1.16.5 with mod version 3.5 beta 4 again.

**Comment by peterwyy** [comment]
I am sorry, this seemed to be a problem with my server. Another reproduction in my server now works.

**Comment by peterwyy** [comment]
I am sorry, this seemed to be a problem with my server. Another trial both local and on my server now works. It might have been due to a connection problem.
