### ISSUE TITLE
Crash trying to load a world with the mod active

### ISSUE THREAD

**Issue by zacharyman1mil** [Tslat/Advent-Of-Ascension#2914]
recent updates to one or more mods used alongside this one has caused the game to crash while generating a world. this problem is consistent across multiple modpacks that all start working fine after disabling this one.
https://paste.gg/p/anonymous/d0b325f5097d458ead439df109713baf

**Comment by Mikecolle** [comment]
are you running thermal and what forge version, ive been dealing with this ever since upgrading to the security fixed forge, 36.2.20. spent the last 12 hours in the cofh discord with people tracking the crash down to this one mod

**Comment by Tslat** [comment]
Yes it's to do with the chiller recipe, but I'm not sure why it's suddenly crashing
You can remove the chiller recipe json from the mod jar and it should fix it, until I release a fixed version anyway

**Comment by Mikecolle** [comment]
whats the name of the recipe i need to remove im so lost

**Comment by Mikecolle** [comment]
removed the whole chiller folder and its still failing to start on the server side

**Comment by Tslat** [comment]
Did you remove it on the server side?

**Comment by Mikecolle** [comment]
yes its 100% a conflict or issue with the thermal recipes as a whole, deleting the whole thermal folder allowed the server to start. Lemming is also looking into this to see if its a tag issue

**Comment by Tslat** [comment]
Let me know if he finds anything

I haven't had the chance to look yet
